### ISSUE TITLE
Investigate a simpler logo

### ISSUE THREAD

**Issue by leereamsnyder** [OSLC/redesign#1]
See [the page on logo concepts](http://oslc.github.io/redesign/posts/logo.html) for more details

Our current "aperture" logo has a couple of issues:

![logo-2011-color-adjusted](https://f.cloud.github.com/assets/870668/2402753/542ecf84-aa26-11e3-9315-53a02271b7b5.png)

- Too many colors
- Many file details limit how much it can be resized
- Hard to use in a variety of applications (too complex, too many colors)

I'd like to move to a simpler logo, like this:

![oslc-loop-v2](https://f.cloud.github.com/assets/870668/2402761/75bfe692-aa26-11e3-912a-c6ba250cf0c8.png)

Again, [more thoughts on it here](http://oslc.github.io/redesign/logo.html) but here's the main benefits:

- much simpler to construct
- holds up to dramatic resizing, large and small
- can be any color, basically
- it's a giant "O"

Thoughts?

**Comment by jscheckla** [comment]
Does anyone have a hi-res version of the new logo.  Mentor needs it for signage at an event.  Everything we can pull from the OSLC Web site is too low resolution to print accurately.

**Comment by leereamsnyder** [comment]
@jscheckla how large do you need?

**Comment by jscheckla** [comment]
Lee,

If we could get Vector art (EPS, SVG, etc.), it doesn’t matter about the size.  If not, then please send as large as you can.  Thanks loads.

Jayne Scheckla
Marketing Programs Manager
System Level Engineering Division
Mentor Graphics

**Comment by leereamsnyder** [comment]
cc @jscheckla 

[Here it is at 4000px](https://cloud.githubusercontent.com/assets/870668/7033021/ea28a558-dd44-11e4-90a4-a12242989483.png)

[SVG version here](https://github.com/OSLC/redesign/blob/gh-pages/_harp/assets/icons/_svgs/logo-med.svg), adjust the width and height to taste

**Comment by jscheckla** [comment]
Thank you so much!
